name: default
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.8
    - numpy=1.21.2
    - pandas=1.3.2
    #- jupyterlab=3.1.7
    - scipy=1.6.2
    - statsmodels=0.13.0
    - tqdm=4.48.0
    - requests
    - multiprocess
    #- rpy2=3.4.5
    #- r-essentials=3.6.0
    #- networkx=2.6.2

